services:
  platform:
    container_name: platform
    build:
      context: .
    restart: always
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000 --verbosity 3
      "
    volumes:
      - .:/app
    ports:
      - 8111:8000
    env_file:
      - .env
    depends_on:
      - platform-db

  platform-db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}


volumes:
  postgres-data: